### PR TITLE
tools: return exit code from kiwi-ng

### PR DESCRIPTION
**Pull request by kshtsk**
tee is hiding exit code from kiwi-ng correspondingly
does not report about an error

Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
jenkins run build-image

**Comment by kshtsk** [comment]
jenkins run build-image

**Comment by kshtsk** [comment]
jenkins run build-image

**Comment by kshtsk** [comment]
jenkins run build-image

**Comment by kshtsk** [comment]
jenkins run build-image

**Review by jecluis — APPROVED** [review]

**Pull request merged**
