### PR TITLE
Add support for isort

### PR DESCRIPTION
**Pull request by jhesketh**
To further help with consistency across files, use isort to ensure
python imports are done in a logical and predictable way.

### CODE REVIEW

**Comment by AvengerMoJo** [comment]
jenkins run leap

**Comment by AvengerMoJo** [comment]
jenkins run tumbleweed

**Comment by AvengerMoJo** [comment]
@jhesketh could we include the steps how to apply isort so we can check our consistency as well. Thanks

**Comment by jhesketh** [comment]
> @jhesketh could we include the steps how to apply isort so we can check our consistency as well. Thanks

Good idea. These are run the same way as the current black tooling, so `tox -e lint` to check things, and `tox -e fixlint` for auto formatting. I'll add these as a followup to the docs.

**Comment by jhesketh** [comment]
Added some extra docs in #629

**Comment by jhesketh** [comment]
jenkins run tumbleweed

**Comment by kshtsk** [comment]
jenkins run opensuse

**Review by jecluis — APPROVED** [review]

**Pull request merged**
