### PR TITLE
[tools]: [Vagrant setup include VirtualBox image type]

### PR DESCRIPTION
**Pull request by AvengerMoJo**
Allow auto detect image type to include provider e.g. libvirt
Or if the image type is VirtualBox it will use VirtualBox syntax

Signed-off-by: Alex Lau (AvengerMoJo) <alau@suse.com>

## Checklist
- [ ] References issues, create if required
- [*] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tserong** [comment]
I did some quick testing. The image type when listing images seems to work fine:
```
> ./aqrdev image list
* aquarium (libvirt)
* main-20210428 (libvirt)
* virtualbox-test (virtualbox)
```

But there's a problem when listing boxes. Without this changeset, I get:

```
> ./aqrdev box list
● SLE12-SP3 (0 deployments)
● SUSE/SLE-15-SP1 (0 deployments)
● aquarium (0 deployments)
● main-20210428 (1 deployments)
```

With this changeset, the deployment count is wrong (see the last line):

```
./aqrdev box list
● SLE12-SP3 (0 deployments) [provider libvirt]
● SUSE/SLE-15-SP1 (0 deployments) [provider libvirt]
● aquarium (0 deployments) [provider libvirt]
● main-20210428 (0 deployments) [provider libvirt]
```

**Comment by kshtsk** [comment]
Since we have a new tool in python, and there are some code units begin to shape up, maybe, it is time to add some unit tests, for example to cover the issue Tim's found?

**Comment by AvengerMoJo** [comment]
> I did some quick testing. The image type when listing images seems to work fine:
> 
> ```
> > ./aqrdev image list
> * aquarium (libvirt)
> * main-20210428 (libvirt)
> * virtualbox-test (virtualbox)
> ```
> 
> But there's a problem when listing boxes. Without this changeset, I get:
> 
> ```
> > ./aqrdev box list
> ● SLE12-SP3 (0 deployments)
> ● SUSE/SLE-15-SP1 (0 deployments)
> ● aquarium (0 deployments)
> ● main-20210428 (1 deployments)
> ```
> 
> With this changeset, the deployment count is wrong (see the last line):
> 
> ```
> ./aqrdev box list
> ● SLE12-SP3 (0 deployments) [provider libvirt]
> ● SUSE/SLE-15-SP1 (0 deployments) [provider libvirt]
> ● aquarium (0 deployments) [provider libvirt]
> ● main-20210428 (0 deployments) [provider libvirt]
> ```

Thanks for the testing I forget to update the deployment function. It is fix now.

**Comment by AvengerMoJo** [comment]
> Since we have a new tool in python, and there are some code units begin to shape up, maybe, it is time to add some unit tests, for example, to cover the issue Tim's found?
Any suggestion? I am not sure I understand what your test tool, could you send me some kind of example? Thanks

**Comment by kshtsk** [comment]
> > Since we have a new tool in python, and there are some code units begin to shape up, maybe, it is time to add some unit tests, for example, to cover the issue Tim's found?
> 
> Any suggestion? I am not sure I understand what your test tool, could you send me some kind of example? Thanks

new tool = aqrdev

**Comment by asettle** [comment]
@AvengerMoJo what's the update on this PR?

**Comment by AvengerMoJo** [comment]
I'm taking this down for now. Nobody is really using it except me.

**Pull request closed without merging**
