### PR TITLE
tools/setup-dev: use nodejs 16.x instead of 15.x

### PR DESCRIPTION
**Pull request by kshtsk**
The nodejs 15.x is deprecated and not actively supported anymore.
It is kindly adviced to switch to any of 12.x, 14.x or 16.x

Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>

## Checklist
- [ ] References issues, create if required
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins test tumbleweed`
- `jenkins run tumbleweed`
- `jenkins test leap`
- `jenkins run leap`

</details>

### CODE REVIEW

**Comment by kshtsk** [comment]
jenkins run ubuntu

**Comment by kshtsk** [comment]
jenkins run ubuntu

**Comment by kshtsk** [comment]
jenkins run leap

**Comment by kshtsk** [comment]
jenkins run tumbleweed

**Comment by kshtsk** [comment]
jenkins run tumbleweed

**Comment by kshtsk** [comment]
jenkins run ubuntu

**Review by AvengerMoJo — COMMENTED** [review]
looks good

**Comment by jecluis** [comment]
maybe we should move all development to node 16 then? @votdev thoughts?

**Comment by kshtsk** [comment]
jenkins test ubuntu

**Comment by kshtsk** [comment]
jenkins test tumbleweed

**Review by AvengerMoJo — APPROVED** [review]

**Comment by AvengerMoJo** [comment]
jenkins test tumbleweed

**Comment by AvengerMoJo** [comment]
jenkins test ubuntu

**Pull request merged**
