### PR TITLE
tools: setup-dev.sh: check for python >= 3.8

### PR DESCRIPTION
**Pull request by tserong**
This ensures we've got at least python 3.8, which is what we use in our images, and is required for asyncio (it's not impossible 3.7 might work, but nobody's tested that so it seems safest to stick with 3.8).

I've also made it a bit more obvious when dependency installation fails.  I've seen cases where zypper fails to refresh some repo, but that scrolls off the top of the screen, the script bails out and all you see at the bottom is the "Nothing to do" line from zypper, so you just assume there's nothing to do.

Signed-off-by: Tim Serong <tserong@suse.com>

## Checklist
- [ ] References issues, create if required
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins test tumbleweed`
- `jenkins run tumbleweed`
- `jenkins test leap`
- `jenkins run leap`

</details>

### CODE REVIEW

**Comment by tserong** [comment]
This breaks jenkins/setup-vagrant-leap, because leap only has python 3.6.12.

This commit was intended to ensure people hacking on Aquarium have the correct version of python. If you've got python 3.6, for example, the unit tests fail with "AttributeError: module 'asyncio' has no attribute 'create_task'" and the flake8 tests fail with "F407 future feature annotations is not defined".

Given we require python 3.8 for development, maybe we should stop testing on leap? What do y'all think?

**Comment by jhesketh** [comment]
> This breaks jenkins/setup-vagrant-leap, because leap only has python 3.6.12.
> 
> This commit was intended to ensure people hacking on Aquarium have the correct version of python. If you've got python 3.6, for example, the unit tests fail with "AttributeError: module 'asyncio' has no attribute 'create_task'" and the flake8 tests fail with "F407 future feature annotations is not defined".
> 
> Given we require python 3.8 for development, maybe we should stop testing on leap? What do y'all think?

We've had a bit of this conversation on https://github.com/aquarist-labs/aquarium/issues/361

My opinion is that we should only support 3.8. We can provide some tips on how a developer might get that (eg through pyenv). If we expect a lot of developers to be using a particular path (eg pyenv on leap), then we should have our test validate that.

**Comment by kshtsk** [comment]
Don't you think the setup-dev.sh script should have a --pyenv option in order to install pyenv from source and install python3.8, having it default on Leap?

**Comment by kshtsk** [comment]
I wonder if we ask to use pyenv python3.8 how the librados system package can be used if it is 3.6 on Leap?

**Comment by kshtsk** [comment]
```
> rpm -ql python3-rados
/usr/lib64/python3.6/site-packages/rados-2.0.0-py3.6.egg-info
/usr/lib64/python3.6/site-packages/rados-2.0.0-py3.6.egg-info/PKG-INFO
/usr/lib64/python3.6/site-packages/rados-2.0.0-py3.6.egg-info/SOURCES.txt
/usr/lib64/python3.6/site-packages/rados-2.0.0-py3.6.egg-info/dependency_links.txt
/usr/lib64/python3.6/site-packages/rados-2.0.0-py3.6.egg-info/top_level.txt
/usr/lib64/python3.6/site-packages/rados.cpython-36m-x86_64-linux-gnu.so
```

**Comment by kshtsk** [comment]
and even if try and use pyenv that mean we should probably use librados from the ceph source tree, don't we?

**Review by jecluis — APPROVED** [review]
with #403 now merged, I believe this is mandatory.

**Comment by tserong** [comment]
> with #403 now merged, I believe this is mandatory.

OK, merged. We can continue pyenv etc. discussion in #361

**Pull request merged**
