### PR TITLE
tools: add error_exit and usage_error_exit

### PR DESCRIPTION
**Pull request by kshtsk**
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
jenkinst test build-image

**Comment by kshtsk** [comment]
jenkins test build-image

**Comment by kshtsk** [comment]
jenkins test setup-dev

**Comment by kshtsk** [comment]
jenkins test setup-dev

**Comment by kshtsk** [comment]
jenkins test build-image

**Comment by kshtsk** [comment]
jenkins test setup-dev

**Comment by kshtsk** [comment]
jenkins test setup-dev

**Comment by kshtsk** [comment]
jenkins test setup-dev

**Comment by kshtsk** [comment]
jenkins run buildimage

**Comment by kshtsk** [comment]
jenkins run setupdev

**Comment by kshtsk** [comment]
jenkins test build-image

**Comment by kshtsk** [comment]
jenkins test build-image

**Comment by kshtsk** [comment]
jenkins test build-image

**Comment by kshtsk** [comment]
jenkins test build-image

**Review by jecluis — APPROVED** [review]

**Pull request merged**
