### PR TITLE
requirements: use aquarist-labs's aetcd3 fork

### PR DESCRIPTION
**Pull request by jecluis**
And fix to a specific sha instead of a branch name.

Signed-off-by: Joao Eduardo Luis \<joao@suse.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
jenkins run tumbleweed

**Review by jhesketh — APPROVED** [review]
Would it be better to pin to a tag? Either way lgtm.

**Comment by jecluis** [comment]
I'll be happy to pin it to a tag if we end up carrying this fork and depending on it. Until then, I'd rather not introducing our tags on that history. Maybe I'm being overzealous/paranoid :shrug:

**Review by tserong — COMMENTED** [review]
This removes `#egg=aetcd3` from the end of the URLs. Does that matter? (I assume it doesn't matter, or the tests would have failed? But https://pip.pypa.io/en/stable/reference/pip_install/#git always puts #egg=... on the end so thought I'd check).

I'm ambivalent about whether we use a SHA or tag for this, but agree that either one is preferable to a branch (the head of which might change).

**Comment by jecluis** [comment]
> This removes `#egg=aetcd3` from the end of the URLs. Does that matter? (I assume it doesn't matter, or the tests would have failed? But https://pip.pypa.io/en/stable/reference/pip_install/#git always puts #egg=... on the end so thought I'd check).

It does. pip was throwing a fit keeping that there because I had this brilliant idea of changing the package's name to `aquarium-aetcd3` in `setup.py` and the egg name and the package's name did not match. So I dropped the one that was less annoying.

Now the library is installed in an `aquarium-etcd` directory, but the library is still used using the `aetcd3` package.

**Pull request merged**
