### PR TITLE
gravel: add pytest coverage report

### PR DESCRIPTION
**Pull request by mgfritch**
```
----------- coverage: platform linux, python 3.8.9-final-0 -----------
Name                                        Stmts   Miss  Cover
---------------------------------------------------------------
gravel/cephadm/cephadm.py                      93     34    63%
gravel/cephadm/models.py                      118      0   100%
gravel/controllers/config.py                   63      0   100%
gravel/controllers/errors.py                    8      3    62%
gravel/controllers/gstate.py                  116     39    66%
gravel/controllers/kv.py                       76     46    39%
gravel/controllers/nodes/bootstrap.py          83     45    46%
gravel/controllers/nodes/conn.py               81     38    53%
gravel/controllers/nodes/deployment.py        208    124    40%
gravel/controllers/nodes/errors.py             23      0   100%
gravel/controllers/nodes/etcd.py               66     51    23%
gravel/controllers/nodes/messages.py           27      0   100%
gravel/controllers/nodes/mgr.py               356    228    36%
gravel/controllers/orch/ceph.py               228    129    43%
gravel/controllers/orch/cephfs.py              69     49    29%
gravel/controllers/orch/models.py             165      0   100%
gravel/controllers/orch/nfs.py                 93     49    47%
gravel/controllers/orch/orchestrator.py        52     34    35%
gravel/controllers/resources/devices.py        91     53    42%
gravel/controllers/resources/inventory.py      56     23    59%
gravel/controllers/resources/status.py         76     32    58%
gravel/controllers/resources/storage.py        64     20    69%
gravel/controllers/services.py                252    158    37%
gravel/controllers/utils.py                    22      5    77%
---------------------------------------------------------------
TOTAL                                        2486   1160    53%
```

Signed-off-by: Michael Fritch <mfritch@suse.com>

## Checklist
- [ ] References issues, create if required
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins test tumbleweed`
- `jenkins run tumbleweed`
- `jenkins test leap`
- `jenkins run leap`

</details>

### CODE REVIEW

**Comment by jhesketh** [comment]
I'm not sure why this is failing since main built fine previously.

You mentioned #460 fixes it. Have you tried rebasing this onto there?

I wonder if the codecov is causing pytest to maintain something such as a module level global. #460 does remove most of those (I think there is still one left), so it may help.

**Review by jhesketh — DISMISSED** [review]
The change itself looks good, but the failure is odd.

**Comment by mgfritch** [comment]
> I'm not sure why this is failing since main built fine previously.
> 
> I wonder if the codecov is causing pytest to maintain something such as a module level global. #460 does remove most of those (I think there is still one left), so it may help.

I don't think it's related to this PR, these failures have been occurring on the main branch in general for the last week or so.

> You mentioned #460 fixes it. Have you tried rebasing this onto there?
> 
yes, rebased to include #460

**Comment by mgfritch** [comment]
unittest coverage improved via #460 :tada: 

```
  ---------- coverage: platform linux, python 3.8.10-final-0 -----------
  Name                                        Stmts   Miss  Cover
  ---------------------------------------------------------------
  aquarium.py                                    78     35    55%
  gravel/api/bootstrap.py                        61     34    44%
  gravel/api/devices.py                          11      1    91%
  gravel/api/local.py                            36     12    67%
  gravel/api/nfs.py                              92     55    40%
  gravel/api/nodes.py                            26      7    73%
  gravel/api/orch.py                             78     37    53%
  gravel/api/services.py                         82     43    48%
  gravel/api/status.py                           38     19    50%
  gravel/cephadm/cephadm.py                      92     35    62%
  gravel/cephadm/models.py                      118      0   100%
  gravel/controllers/config.py                   68      0   100%
  gravel/controllers/errors.py                    8      3    62%
  gravel/controllers/gstate.py                  127     12    91%
  gravel/controllers/kv.py                       80     49    39%
  gravel/controllers/nodes/bootstrap.py          85     45    47%
  gravel/controllers/nodes/conn.py               81     38    53%
  gravel/controllers/nodes/deployment.py        208    119    43%
  gravel/controllers/nodes/errors.py             23      0   100%
  gravel/controllers/nodes/etcd.py               67     52    22%
  gravel/controllers/nodes/messages.py           27      0   100%
  gravel/controllers/nodes/mgr.py               354    214    40%
  gravel/controllers/orch/ceph.py               243    143    41%
  gravel/controllers/orch/cephfs.py              68     48    29%
  gravel/controllers/orch/models.py             165      0   100%
  gravel/controllers/orch/nfs.py                 93     49    47%
  gravel/controllers/orch/ntp.py                 20     14    30%
  gravel/controllers/orch/orchestrator.py        52     34    35%
  gravel/controllers/resources/devices.py        93     52    44%
  gravel/controllers/resources/inventory.py      58      4    93%
  gravel/controllers/resources/status.py         74     29    61%
  gravel/controllers/resources/storage.py        65     19    71%
  gravel/controllers/services.py                252    114    55%
  gravel/controllers/utils.py                    22      3    86%
  ---------------------------------------------------------------
  TOTAL                                        3045   1319    57%
```

**Review by jecluis — APPROVED** [review]

**Comment by jhesketh** [comment]
> > I'm not sure why this is failing since main built fine previously.
> > I wonder if the codecov is causing pytest to maintain something such as a module level global. #460 does remove most of those (I think there is still one left), so it may help.
> 
> I don't think it's related to this PR, these failures have been occurring on the main branch in general for the last week or so.

Hmm okay.

I wonder if it's related to the multiprocessing spawn method that was causing me some issues (fixed in 460).

Either way, lets keep an eye on it and see if it keeps happening or hopefully if it's fixed.

> 
> > You mentioned #460 fixes it. Have you tried rebasing this onto there?
> 
> yes, rebased to include #460

**Review by jhesketh — APPROVED** [review]
lgtm!

**Pull request merged**
