### PR TITLE
tools: rename aqrdev to aqua

### PR DESCRIPTION
**Pull request by kshtsk**
## Checklist
- [ ] References issues, create if required
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins test tumbleweed`
- `jenkins run tumbleweed`
- `jenkins test leap`
- `jenkins run leap`

</details>

### CODE REVIEW

**Comment by kshtsk** [comment]
jenkins run tumbleweed

**Comment by kshtsk** [comment]
jenkins run ubuntu

**Review by AvengerMoJo — COMMENTED** [review]
look good

**Comment by kshtsk** [comment]
jenkins run tumbleweed

**Comment by jhesketh** [comment]
What is the reasoning for renaming? Personally I find aqrdev to be clearer in its purpose.

**Comment by kshtsk** [comment]
> What is the reasoning for renaming? Personally I find aqrdev to be clearer in its purpose.

we discussed this on the channel and on meetings, mostly because it is difficult to pronounce.

**Comment by jhesketh** [comment]
> > What is the reasoning for renaming? Personally I find aqrdev to be clearer in its purpose.
> 
> we discussed this on the channel and on meetings, mostly because it is difficult to pronounce.

Okay. I disagree as I tend to read it as "Aqua dev" rather than trying to read it phonetically. That said, I hold no stakes in this and if others want it changed then sure.

**Comment by jecluis** [comment]
I'd suggest doing `aquadev` instead, and keep the name `aqua` for something a bit more interesting down the line. Seems wasteful to spend such a nice name with a dev tool :shrug:

**Comment by kshtsk** [comment]
> > > What is the reasoning for renaming? Personally I find aqrdev to be clearer in its purpose.
> > 
> > 
> > we discussed this on the channel and on meetings, mostly because it is difficult to pronounce.
> 
> Okay. I disagree as I tend to read it as "Aqua dev" rather than trying to read it phonetically. That said, I hold no stakes in this and if others want it changed then sure.

I am not following what do you read as 'aqua dev', if you read 'aqrdev' then it is wrong. If you read 'aqua' as 'aqua dev' it is wrong, aqua is aqua, where do you see dev.

**Comment by kshtsk** [comment]
> I'd suggest doing `aquadev` instead, and keep the name `aqua` for something a bit more interesting down the line. Seems wasteful to spend such a nice name with a dev tool 🤷

I don't like 'aquadev' it is too long. 'aqua' is dev tool for aquarium. If you call 'aquadev' it is something that for developing aqua, not aquarium.

**Comment by kshtsk** [comment]
@jhesketh @jecluis we already took a decision on taking aqua, this PR didn't not appear from only my head unexpectedly.
I suggest to merge it as is, if anyone want to change name, let's discuss it again in chat, raise compute votes, and someone not me create another PR.

**Comment by jhesketh** [comment]
> > > > What is the reasoning for renaming? Personally I find aqrdev to be clearer in its purpose.
> > > 
> > > 
> > > we discussed this on the channel and on meetings, mostly because it is difficult to pronounce.
> > 
> > 
> > Okay. I disagree as I tend to read it as "Aqua dev" rather than trying to read it phonetically. That said, I hold no stakes in this and if others want it changed then sure.
> 
> I am not following what do you read as 'aqua dev', if you read 'aqrdev' then it is wrong. If you read 'aqua' as 'aqua dev' it is wrong, aqua is aqua, where do you see dev.

I mean that if I were to refer to `aqrdev` out loud I would pronounce it as "aqua dev". Whether or not it's correct is subjective. But that's beside the point, which is that I don't feel strongly either way about this (was merely giving an opinion), and I'm happy for whatever others choose.

**Comment by kshtsk** [comment]
> > > > > What is the reasoning for renaming? Personally I find aqrdev to be clearer in its purpose.
> > > > 
> > > > 
> > > > we discussed this on the channel and on meetings, mostly because it is difficult to pronounce.
> > > 
> > > 
> > > Okay. I disagree as I tend to read it as "Aqua dev" rather than trying to read it phonetically. That said, I hold no stakes in this and if others want it changed then sure.
> > 
> > 
> > I am not following what do you read as 'aqua dev', if you read 'aqrdev' then it is wrong. If you read 'aqua' as 'aqua dev' it is wrong, aqua is aqua, where do you see dev.
> 
> I mean that if I were to refer to `aqrdev` out loud I would pronounce it as "aqua dev".

This is a problem because aqrdev is not aqua dev at all, it is short for AQuaRium DEVelopment. And when you say "aqua dev" orally it not clear what exact command name to type, especially for newbies.

> Whether or not it's correct is subjective. But that's beside the point, which is that I don't feel strongly either way about this (was merely giving an opinion), and I'm happy for whatever others choose.

**Comment by kshtsk** [comment]
jenkins run tumbleweed

**Comment by jecluis** [comment]
@kshtsk is there any particular reason why we should no longer merge this PR?

**Comment by kshtsk** [comment]
> @kshtsk is there any particular reason why we should no longer merge this PR?

No one literally approved for the period of time about a week.

**Comment by jecluis** [comment]
> 
> 
> > @kshtsk is there any particular reason why we should no longer merge this PR?
> 
> No one literally approved for the period of time about a week.

Things have been in a lull, and things have fallen through the cracks. Doesn't mean we don't want it, just happened. I'm up to approving it if this is still something you want to merge.

**Comment by kshtsk** [comment]
> > > @kshtsk is there any particular reason why we should no longer merge this PR?
> > 
> > 
> > No one literally approved for the period of time about a week.
> 
> Things have been in a lull, and things have fallen through the cracks. Doesn't mean we don't want it, just happened. I'm up to approving it if this is still something you want to merge.

Yes I do.

**Review by jecluis — APPROVED** [review]
lgtm

**Pull request merged**
