### PR TITLE
glass: join cluster form - add port number field

### PR DESCRIPTION
**Pull request by votdev**
Peek 2021-05-17 16-19

- Rename component to InstallRegisterPageComponent

Fixes: https://github.com/aquarist-labs/aquarium/issues/455

Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- [x] References issues, create if required
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins test tumbleweed`
- `jenkins run tumbleweed`
- `jenkins test leap`
- `jenkins run leap`

</details>

### CODE REVIEW

**Review by jecluis — COMMENTED** [review]
@votdev this looks really good. any chance the ticker thingy on the right hand side of the port field can be hidden?

**Comment by votdev** [comment]
jenkins test tumbleweed

**Comment by votdev** [comment]
jenkins run tumbleweed

**Comment by votdev** [comment]
> @votdev this looks really good. any chance the ticker thingy on the right hand side of the port field can be hidden?

Done

**Review by jecluis — APPROVED** [review]

**Pull request merged**
