### PR TITLE
glass: Add services page

### PR DESCRIPTION
**Pull request by votdev**
Bildschirmfoto vom 2021-03-18 16-48-25

This is the core service page. In follow up PRs the ability to edit/delete them will be added. It is also planned to enhance the visualized data per service.

Signed-off-by: Volker Theile <vtheile@suse.com>

### CODE REVIEW

**Comment by asettle** [comment]
This looks really good!

**Review by jecluis — DISMISSED** [review]
LGTM - although I do have concerns about "Usable size" instead of "Allocated size", but I think this is a broader discussion we need to have sooner rather than later.

**Comment by votdev** [comment]
> LGTM - although I do have concerns about "Usable size" instead of "Allocated size", but I think this is a broader discussion we need to have sooner rather than later.

I'm fine with changing that.

**Review by s0nea — APPROVED** [review]
LGTM!

I'm only wondering if _CephFS Share_ should be renamed into _CephFS Service_ (just to be consistent with the wording).

Screenshot_2021-03-29_13-29-25

Also I created https://github.com/aquarist-labs/aquarium/issues/345 which can be addressed separately in my opinion.

**Comment by votdev** [comment]
> LGTM!
> 
> I'm only wondering if _CephFS Share_ should be renamed into _CephFS Service_ (just to be consistent with the wording).
> 
> Screenshot_2021-03-29_13-29-25
> 
> Also I created #345 which can be addressed separately in my opinion.

I agree we have to polish the wording here and there in the UI. I took over the ' CephFS Share` from the services dashboard widget. So we have to adapt it there,too.

**Pull request merged**
