### PR TITLE
image: fix microos config.xml according to upstream

### PR DESCRIPTION
**Pull request by jecluis**
Signed-off-by: Joao Eduardo Luis \<joao@suse.com>

## Checklist
- [ ] References issues, create if required
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins run tumbleweed`
- `jenkins run leap`
- `jenkins run ubuntu`

</details>

### CODE REVIEW

**Comment by s0nea** [comment]
jenkins run tumbleweed

**Comment by jecluis** [comment]
jenkins run tumbleweed

**Review by s0nea — APPROVED** [review]
Thanks! - It fixes the issue on my environment.

**Comment by kshtsk** [comment]
jenkins run tumbleweed

**Comment by kshtsk** [comment]
jenkins run tumbleweed

**Comment by kshtsk** [comment]
jenkins run tumbleweed

**Comment by kshtsk** [comment]
> @kshtsk can you please take a look at what's happening with the tumbleweed run? Seems to be failing updating packages on the image.

I uploaded latest jeos image, and it is failing in a different way now. Something wrong with it.

**Comment by kshtsk** [comment]
jenkins run tumbleweed

**Comment by kshtsk** [comment]
hm... I suspect it is the issue with:
```userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]```

looks liike paramiko cannot handle it, however I can log into to the node manually

**Comment by kshtsk** [comment]
jenkins run tumbleweed

**Review by kshtsk — APPROVED** [review]

**Pull request merged**
