### PR TITLE
[tools] Add authentication support to smoke tests

### PR DESCRIPTION
**Pull request by votdev**
- Add authenticate support to smoke tests
- Add option to aqrtest.py to skip adding the Vagrant image

Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- [ ] References issues, create if required
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins test tumbleweed`
- `jenkins run tumbleweed`
- `jenkins test leap`
- `jenkins run leap`

</details>

### CODE REVIEW

**Comment by kshtsk** [comment]
jenkins run tumbleweed

**Comment by kshtsk** [comment]
jenkins run tumbleweed

**Comment by kshtsk** [comment]
jenkins run tumbleweed

**Comment by kshtsk** [comment]
jenkins run tumbleweed

**Review by jhesketh — APPROVED** [review]

**Comment by votdev** [comment]
jenkins run tumbleweed

**Pull request merged**
