### PR TITLE
glass: Update logo images

### PR DESCRIPTION
**Pull request by votdev**
Use SVG as origin image to generate the favicons.

Before:
Bildschirmfoto vom 2021-04-21 08-10-58

After:
Bildschirmfoto vom 2021-04-21 08-05-34

Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- [ ] References issues, create if required
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins test tumbleweed`
- `jenkins run tumbleweed`
- `jenkins test leap`
- `jenkins run leap`

</details>

### CODE REVIEW

**Comment by votdev** [comment]
@kshtsk Finally i used your SVG instead of mine because yours have less nodes and looked a little bit smoother than mine (which was not optimized via Inkscape).

**Comment by tserong** [comment]
I made two tiny tweaks to kyr's version, to remove a couple of pointy bits from the left hand two tentacles and dropped it in the slack channel - do you mind using that one?

**Comment by votdev** [comment]
> I made two tiny tweaks to kyr's version, to remove a couple of pointy bits from the left hand two tentacles and dropped it in the slack channel - do you mind using that one?

Yes, will adapt the PR accordingly.

**Review by tserong — APPROVED** [review]
Thanks!

**Pull request merged**
