### PR TITLE
aquarium: reflect reality, license under GPL3

### PR DESCRIPTION
**Pull request by jecluis**
Signed-off-by: Joao Eduardo Luis \<joao@suse.com>

### CODE REVIEW

**Comment by l-mb** [comment]
Just for the record: have you checked that the new '*' coverage doesn't accidentally cover any files that are indeed on a different license?

**Review by asettle — DISMISSED** [review]

**Review by jhesketh — DISMISSED** [review]

**Comment by jhesketh** [comment]
I wonder if this is considered something that needs every contributor to agree to in case it could have been interpreted as every file being dual license and we're removing one?

**Comment by jecluis** [comment]
> I wonder if this is considered something that needs every contributor to agree to in case it could have been interpreted as every file being dual license and we're removing one?

@jhesketh So far all contributors' copyright holder has been SUSE, and the agreement when we were starting the project was GPL3; and pretty much all the files have headers under GPL3. I'd say this is a nonissue.

> Just for the record: have you checked that the new '*' coverage doesn't accidentally cover any files that are indeed on a different license?

@l-mb AFAICT we're not covering  anything else that is not covered by another portion of the COPYING file. But we can adjust the wording to `unless otherwise specified` just in case.

**Review by l-mb — APPROVED** [review]
LGTM, thanks for the clarification.

**Comment by asettle** [comment]
@jecluis are you waiting on any further reviews or can this be merged?

**Comment by jecluis** [comment]
@asettle @l-mb just repushed, adding an `unless otherwise specified` to the wildcard entry in the COPYING file.

**Review by asettle — APPROVED** [review]

**Pull request merged**
