### PR TITLE
wasser: add extra check for aquarium service is running

### PR DESCRIPTION
**Pull request by kshtsk**
## Checklist
- [ ] References issues, create if required
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins test tumbleweed`
- `jenkins run tumbleweed`
- `jenkins test leap`
- `jenkins run leap`

</details>

### CODE REVIEW

**Review by votdev — APPROVED** [review]

**Comment by kshtsk** [comment]
The next fail is due to main is broken:
```
12:19:25 >>> ==> node1: Creating shared folders metadata...
12:19:25 EEE Error while activating network: Call to virNetworkCreate failed: internal error: Failed to initialize a valid firewall backend.
12:19:25 >>> Deployment 'foo' started
```

**Comment by kshtsk** [comment]
Reported the issue as a bug for aqrdev #533

**Comment by kshtsk** [comment]
Note, with resolution of #533 the failure will not go away though, because the real reason of the libvirt error should be fixed.

**Comment by kshtsk** [comment]
@jecluis JFYI

**Pull request merged**
