### PR TITLE
.wasser/config: use same routine for Leap and Tumbleweed

### PR DESCRIPTION
**Pull request by kshtsk**
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@gmail.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
jenkins test tumbleweed

**Comment by kshtsk** [comment]
jenkins test tumbleweed

**Comment by kshtsk** [comment]
jenkins test tumbleweed

**Comment by kshtsk** [comment]
jenkins test tumbleweed

**Comment by kshtsk** [comment]
jenkins test tumbleweed

**Comment by kshtsk** [comment]
jenkins run setup-vagrant

**Comment by kshtsk** [comment]
jenkins run setup-vagrant

**Comment by kshtsk** [comment]
jenkins test tumbleweed

**Comment by kshtsk** [comment]
jenkins run setup-vagrant

**Comment by kshtsk** [comment]
jenkins test tumbleweed

**Comment by kshtsk** [comment]
jenkins run setup-vagrant

**Comment by kshtsk** [comment]
jenkins run setup-vagrant

**Comment by kshtsk** [comment]
jenkins test tumbleweed

**Comment by kshtsk** [comment]
jenkins test tumbleweed

**Comment by kshtsk** [comment]
jenkins test tumbleweed

**Comment by kshtsk** [comment]
Tumbleweed host fails with next error:
```
>>> The following SSH command responded with a non-zero exit status.
>>> Vagrant assumes that this means the command failed!
>>> 
>>> mount -o vers=3,udp 192.168.121.1:/home/opensuse/aquarium /srv/aquarium
>>> 
>>> Stdout from the command:
>>> 
>>> 
>>> 
>>> Stderr from the command:
>>> 
>>> mount.nfs: requested NFS version or transport protocol is not supported
```

**Comment by kshtsk** [comment]
jenkins run setup-vagrant

**Comment by jhesketh** [comment]
The NFS issue could be due to iptables. Have you checked those?

If not, it's possibly a permission problem. I had to create the nfs mount in /tmp instead of my home path on my dev machine.

**Comment by kshtsk** [comment]
> The NFS issue could be due to iptables. Have you checked those?
> 
> If not, it's possibly a permission problem. I had to create the nfs mount in /tmp instead of my home path on my dev machine.

No there is no iptables service running, nor firewall. The reason is vagrant tries to mount over udp, which is disabled by default on Tumbleweed nfs.

**Comment by kshtsk** [comment]
jenkins test tumbleweed

**Comment by kshtsk** [comment]
jenkins test tumbleweed

**Comment by kshtsk** [comment]
jenkins test tumbleweed

**Comment by kshtsk** [comment]
jenkinst test tumbleweed

**Comment by kshtsk** [comment]
jenkinst test tumbleweed

**Comment by kshtsk** [comment]
jenkins test tumbleweed

**Comment by kshtsk** [comment]
jenkins test tumbleweed

**Review by jecluis — APPROVED** [review]

**Pull request merged**
