### PR TITLE
glass: add cypress initial basic test

### PR DESCRIPTION
**Pull request by kshtsk**
## Checklist
- [ ] References issues, create if required
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins test tumbleweed`
- `jenkins run tumbleweed`
- `jenkins test leap`
- `jenkins run leap`

</details>

### CODE REVIEW

**Comment by kshtsk** [comment]
jenkins run ubuntu

**Comment by kshtsk** [comment]
jenkins run ubuntu

**Comment by kshtsk** [comment]
jenkins run ubuntu

**Comment by kshtsk** [comment]
jenkins run ubuntu

**Comment by kshtsk** [comment]
jenkins run ubuntu

**Comment by kshtsk** [comment]
jenkins run tumbleweed

**Review by s0nea — APPROVED** [review]
LGTM - which means I was able to run the tests on my local environment and the changes make sense to me as far as I can tell. I'm very keen on getting @callithea's take on the PR as well.

**Review by callithea — APPROVED** [review]
Lgtm, thanks a bunch, @kshtsk!

**Review by votdev — APPROVED** [review]
LGTM, thx.

**Pull request merged**
