### PR TITLE
gravel: pass hostname as parameters to deploy & join (part 1)

### PR DESCRIPTION
**Pull request by jecluis**
We are now passing the user-specified hostname as parameters to the deploy and join endpoints, so we can set the hostname as part of a node's deployment process.

We are also removing the endpoint that allows to set the hostname because we suspect changing a hostname after a node has been deployed will not be a trivial task, and we currently have no other use for this endpoint.

~Depends on #581~

Signed-off-by: Joao Eduardo Luis \<joao@suse.com>

### CODE REVIEW

**Review by jhesketh — APPROVED** [review]

**Comment by AvengerMoJo** [comment]
@jecluis do we need to care to sync the /etc/hosts? or possible DNS support in the future?

**Comment by jecluis** [comment]
> @jecluis do we need to care to sync the /etc/hosts? or possible DNS support in the future?

I'm not sure. Maybe? Although this feels like something that would be external to the cluster, like the same with dhcp etc.

**Comment by jecluis** [comment]
@votdev mind taking a look at the glass bits?

**Review by votdev — APPROVED** [review]

**Comment by jecluis** [comment]
@votdev @s0nea addressed the cosmetic issues; mind reviewing/approving?

**Review by s0nea — APPROVED** [review]

**Pull request merged**
