### PR TITLE
tools: Fix bug when building Glass for images, CI, ...

### PR DESCRIPTION
**Pull request by votdev**
Fixes: https://github.com/aquarist-labs/aquarium/issues/529
Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- [x] References issues, create if required
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins test tumbleweed`
- `jenkins run tumbleweed`
- `jenkins test leap`
- `jenkins run leap`

</details>

### CODE REVIEW

**Review by jecluis — DISMISSED** [review]
LGTM, minus unrelated comment.

**Review by kshtsk — APPROVED** [review]

**Review by kshtsk — DISMISSED** [review]
Wait, the tests looks false positive, aquarium node is not running. We need to double check.

**Comment by jecluis** [comment]
That is likely my fault. It should be fixed now on main.

**Comment by kshtsk** [comment]
jenkins test tumbleweed

**Comment by jecluis** [comment]
oh, okay. So not my fault. My thing would not cause vagrant to bail out.

**Comment by kshtsk** [comment]
If it is fixed on main it should be working here, because tests are running against automerge.

**Comment by kshtsk** [comment]
guys, could you please review #532 so no false positive output of aqrdev and vagrant interfere the testing anymore. Though aqrdev should be fixed to return exit code with error in case it really failed to start the deployment, the vagrant false positive exit code is not that trivial to fix.

**Comment by kshtsk** [comment]
jenkins test tumbleweed

**Comment by kshtsk** [comment]
The #532 is merged, so report the failure now, however the #533 needs to be fixed, and the actually tumbleweed environment failure needs some effort to resolve `Error while activating network: Call to virNetworkCreate failed: internal error: Failed to initialize a valid firewall backend`

**Comment by votdev** [comment]
jenkins run tumbleweed

**Review by jecluis — APPROVED** [review]

**Pull request merged**
