### PR TITLE
ceph.git: update to custom pacific-based branch

### PR DESCRIPTION
**Pull request by jecluis**
The custom branch at 'wip-cephadm-fixes.pacific' contains additional
patches we need to make aquarium work, which have not yet been merged
upstream.

Other than that, this is the pacific branch as of 2021-04-01.

Signed-off-by: Joao Eduardo Luis \<joao@suse.com>

### CODE REVIEW

**Comment by jecluis** [comment]
having issues with cephadm

**Comment by jecluis** [comment]
We'll be carrying two patches until they are merged into pacific upstream.

* fix apparmor thingy: https://github.com/ceph/ceph/pull/40555 (opened against master)
* fix `host add` thingy: https://github.com/ceph/ceph/pull/40554 (opened against pacific)

**Comment by jecluis** [comment]
current tumbleweed failures is due to some fluke with zypper.

**Comment by jecluis** [comment]
jenkins run tumbleweed

**Comment by jecluis** [comment]
the jenkins failure continues to be unrelated:

```
+ wa run .wasser/config.yaml -t aquarium-setup-vagrant-tumbleweed-133 --openstack-cloud=de --github-branch origin/pr/370/merge --github-url https://github.com/aquarist-labs/aquarium
Reading spec from file: .wasser/config.yaml
Found existing servers: 
Looking up image openSUSE-Tumbleweed-JeOS.x86_64-15.1.0-OpenStack-Cloud-Snapshot20210307...
Found image with id: d5199e80-2778-4bf5-8e04-6d25b92a67a5
Found flavor: be7fb6db-3d81-41cc-8e8b-eb4913dffd91
Image:   openSUSE-Tumbleweed-JeOS.x86_64-15.1.0-OpenStack-Cloud-Snapshot20210307
Flavor:  b2-15
Keypair: storage-automation
Traceback (most recent call last):
  File "/home/jenkins/wasser/v/lib/python3.6/site-packages/openstack/cloud/_utils.py", line 425, in shade_exceptions
    yield
  File "/home/jenkins/wasser/v/lib/python3.6/site-packages/openstack/cloud/_compute.py", line 913, in create_server
    if server.status == 'ERROR':
AttributeError: 'NoneType' object has no attribute 'status'
```

And I just finished testing a new image with this pacific version and it's good to go.

**Review by mgfritch — APPROVED** [review]

**Pull request merged**
