### PR TITLE
Multiple aqrdev fixes

### PR DESCRIPTION
**Pull request by kshtsk**
## Checklist
- [ ] References issues, create if required
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins test tumbleweed`
- `jenkins run tumbleweed`
- `jenkins test leap`
- `jenkins run leap`

</details>

### CODE REVIEW

**Review by AvengerMoJo — COMMENTED** [review]
The virtualbox template has another error will may fix that next issue.

**Review by AvengerMoJo — APPROVED** [review]
Let's merge this first and I will commit the next bug fix

**Comment by kshtsk** [comment]
jenkins run tumbleweed

**Comment by kshtsk** [comment]
Looks like tumbleweed repos are not stable again, the failure is not related to this PR.

**Pull request merged**
