### PR TITLE
aquarium: api: move bootstrap to nodes endpoint

### PR DESCRIPTION
**Pull request by jecluis**
Signed-off-by: Joao Eduardo Luis \<joao@suse.com>

### CODE REVIEW

**Comment by jecluis** [comment]
@votdev probably a good idea to merge after #458

**Comment by kshtsk** [comment]
ouch... bummer, the hanging issue still exits :-(

**Comment by kshtsk** [comment]
jenkins test tumbleweed

**Comment by s0nea** [comment]
I guess the PR needs to be rebased. In `main` we now do have another bootstrap service reference which is not part of the PR, e.g.: https://github.com/aquarist-labs/aquarium/blob/main/src/glass/src/app/pages/install-wizard-page/install-wizard-page.component.ts#L181

**Comment by jecluis** [comment]
@s0nea mind another look?

**Review by s0nea — APPROVED** [review]
The glass part LGTM

**Comment by jecluis** [comment]
another change incoming, will make this obsolete.

**Pull request closed without merging**
