### PR TITLE
tools: move run_aquarium.sh to tools

### PR DESCRIPTION
**Pull request by kshtsk**
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>

## Checklist
- [ ] References issues, create if required
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins test tumbleweed`
- `jenkins run tumbleweed`
- `jenkins test leap`
- `jenkins run leap`

</details>

### CODE REVIEW

**Comment by kshtsk** [comment]
jenkins run leap

**Comment by kshtsk** [comment]
jenkins run leap

**Review by tserong — CHANGES_REQUESTED** [review]
LGTM, but also needs an update in doc/from-zero-to-hacking.md where it says `sudo ./run_aquarium.sh`, to say `sudo ./tools/run_aquarium.sh`.

**Comment by jecluis** [comment]
yeah, what @tserong said

**Comment by kshtsk** [comment]
jenkins run tumbleweed

**Comment by kshtsk** [comment]
jenkins run tumbleweed

**Comment by kshtsk** [comment]
jenkins run ubuntu

**Comment by kshtsk** [comment]
jenkins run ubuntu

**Review by AvengerMoJo — APPROVED** [review]
look good to me

**Comment by kshtsk** [comment]
@tserong your blocking review still remains.

**Review by jecluis — APPROVED** [review]

**Pull request merged**
