### PR TITLE
glass: Remove all 'Services' related code

### PR DESCRIPTION
**Pull request by votdev**
Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- [ ] References issues, create if required
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins test tumbleweed`
- `jenkins run tumbleweed`
- `jenkins test leap`
- `jenkins run leap`

</details>

### CODE REVIEW

**Comment by kshtsk** [comment]
e2e test should be fixed accordingly

**Comment by kshtsk** [comment]
like this line https://github.com/aquarist-labs/aquarium/blob/main/src/glass/cypress/integration/dive_into_aquarium.js#L12

**Comment by s0nea** [comment]
I do have the feeling https://github.com/aquarist-labs/aquarium/blob/main/src/glass/src/app/shared/services/api/cephfs.service.ts can be removed as well. Or is there an actual point of keeping it?

**Comment by votdev** [comment]
> I do have the feeling [https://github.com/aquarist-labs/aquarium/blob/main/src/glass/src/app/shared/services/api/cephfs.service.ts](https://github.com/aquarist-labs/aquarium/blob/main/src/glass/src/app/shared/services/api/cephfs.service.ts?rgh-link-date=2021-08-09T13%3A08%3A46Z) can be removed as well. Or is there an actual point of keeping it?

Thx for the hint. Done.

**Review by s0nea — APPROVED** [review]

**Pull request merged**
